---
author: "patrick.unicorn"
output:
  html_document:
    css: ../../css/main.css
    highlight: null
    theme: null
---

Gradle
===

* * *

+ Java构建工具对比

|工具|优点|缺点|
|--|--|--|
|Ant|灵活性、完全控制、目标链|繁琐、不易读、XML表达能力有限|
|Ivy|依赖管理|不是完整的构建工具|
|Maven|约定优于配置、多模块项目、插件扩展|插件不易扩展、XML表达能力有限|
|Gant|基于Ant提供DSL||
|Gradle|博采众家之长、兼容Ant和Maven项目|深入使用需要学习Groovy、学习成本高|

+ Gradle脚本中的每一个元素都有一个Java类一一映射。Gradle基本工作单元是Task，这与Grant类似。

+ Gradle的DSL是由Groovy实现的，所有的构建脚本本身就是Groovy编程语言，甚至可以使用Java去编写脚本，但相比Groovy，会很繁琐。

+ Gradle采用了和Maven类似的指导思想：**约定优于配置**和**规定构建生命周期**。其默认项目结构与maven一致。

<blockquote>
[compile java]/[process resource] -> classes -> jar -> assemble -> build
</blockquote>

+ Maven中一个项目必须只能设定一个源代码目录和生产一个Jar包。而在Gradle中，均可以有多个。Maven太**武断**，而Ant太灵活（没有任何约定默认值），Grandle则**折中取之**。

+ Gradle支持**部分构建**，而不是改动一个**小点**，就需要全局Clean并重新构建。

+ Gradle中定制构建逻辑有两种主要的方法：基于Task和基于插件。后者可以使用Gradle的所有API，并且可以被多个项目重用。

+ Gradle完全兼容Ant、Maven。通过Gradle提供的转换器，可以将Maven构建逻辑转换为Gradle构建脚本。而对于Ant，其target直接映射为Gradle的task。Maven和Ivy的仓库是完全被Gradle支持的。

+ Gradle包装器允许**执行构建的机器**从指定的仓库下载并安装一个Gradle运行时，这对于持续集成服务器或者分享构建非常有用。

+ 可以在**GRADLE_HOME/bin**下的Gradle启动脚本中设置一些启动参数，比如JVM的最大内存等等。

+ Gradle默认的构件脚本文件名是**build.gradle**。

+ `gradle -q <task name>`执行某个task，`-q`表示**quiet**，只输出该task的信息。

+ 定义任务

```
task helloworld {
    doLast {
        println 'Hello World'
    }
}

等价于

task helloworld << {
    println 'Hello World'
}
```

+ 