**声明：** 所写均为个人阅读所思所想，限于知识层次和结构，难免有错误遗漏之处，请批判阅读。探讨可循：<mr.geek.ma@gmail.com>

* * *

## Abstract

#### CAP

> 在理论计算机科学中，CAP定理（CAP theorem），又被称作布鲁尔定理（Brewer's theorem），它指出对于一个分布式计算系统来说，不可能同时满足以下三点：[1][2]
>
> 一致性（Consistency)（等同于所有节点访问同一份最新的数据副本）
> 可用性（Availability）（对数据更新具备高可用性）
> 容忍网络分区（Partition tolerance）（以实际效果而言，分区相当于对通信的时限要求。系统如果不能在时限内达成数据一致性，就意味着发生了分区的情况，必须就当前操作在C和A之间做出选择[3]。）
>
>根据定理，分布式系统只能满足三项中的两项而不可能满足全部三项[4]。理解CAP理论的最简单方式是想象两个节点分处分区两侧。允许至少一个节点更新状态会导致数据不一致，即丧失了C性质。如果为了保证数据一致性，将分区一侧的节点设置为不可用，那么又丧失了A性质。除非两个节点可以互相通信，才能既保证C又保证A，这又会导致丧失P性质。

#### BASE

传统数据库理论ACID的变种，启发于CAP理论。

> Basic Availability：基本可用
> Soft-State ：软状态/柔性事务，可以理解为”无连接”的, 而 “Hard state” 是”面向连接”的
> Eventual consistency：最终一致性，最终整个系统（时间和系统的要求有关）看到的数据是一致

该理论对应于传统的ACID数据库理论

> 原子性(Atomic): 整个事务中的所有操作，要么全部完成，要么全部不完成，不可能停滞在中间某个环节。事务在执行过程中发生错误，会被回滚（Rollback）到事务开始前的状态，就像这个事务从来没有执行过一样。
> 一致性(Consistent): 在事务开始之前和事务结束以后，数据库的完整性约束没有被破坏。
> 隔离性(Isolated): 两个事务的执行是互不干扰的，一个事务不可能看到其他事务运行时，中间某一时刻的数据。 两个事务不会发生交互。
> 持久性(Durable): 在事务完成以后，该事务所对数据库所作的更改便持久的保存在数据库之中，并不会被回滚。
