---
title: "Reading Notes of Implementing DDD"
author: "patrick.unicorn"
date: "Thursday, December 25, 2014"
output: html_document
---

**声明：** 所写均为个人阅读所思所想，限于知识层次和结构，难免有错误遗漏之处，请批判阅读。探讨可循：<mr.geek.ma@foxmail.com>

* * *

**`{:}`** DDD不仅仅是一种设计方法，更是一种设计视角和思维方式。它要求我们必须以核心业务的视角设计对象以及对象交互。传统基于DB系统技术方式更关注业务数据的存储及关联关系，却忽视了业务领域中的**行为活动**，而**业务行为活动**才是业务核心价值的体现。相比基于DB设计而言，基于类设计前进了一小步，但它的缺点也是明显的，它关注对象状态胜于对象行为(交互)。

**`{:}`** 当我们真正以OOP视角去设计系统时，我们其实是在关注**对象**及其**交互行为**，在这一过程中我们会自然而然地导出一组**交互接口**，基于**交互接口**反推出**对象状态**，同时真正实现**基于接口**和**基于抽象**编程。这点与基于DB的系统设计的过程恰好相反。

**`{:}`** DDD中设计就是编码，编码就是设计。必须**将核心领域对象映射构建到代码级别**，而不是设计图纸(如UML)。**领域对象上的方法命名必须准确清晰表达业务活动**。比如我们不能用`update`去命名用于保存用户密码的方法，显然savePassword是更好的命名。

**`{:}`** 领域就是指某个组织机构的业务范围和业务活动。有些领域是“大众化的”，如电子商务、SNS、云计算等等，有些领域是“小众化”的，如金融、机票、酒店、版本管理等等。

**`{:}`** DDD设计的一个重要方面就是必须将领域划分为多个子域，而不是一个大一统的领域单体。

**`{:}`** 领域模型包含两个方面：

+ 领域通用语言

所谓领域通用语言就是开发团队与领域专家一起达成的关于特定领域的若干概念的**共识描述**。通常，可以通过与领域专家的沟通中，总结出领域中的**通用术语**和**业务操作**的概念表述(可以总结为一份术语列表文档)，基于此进而构建领域通用语言。领域模型将通用语言表达为软件模型。

+ 领域限界上线文

限界上下文是一个显示的**语义边界**，在边界之内，通用语言中的特定术语和词组都具有明确无歧义的确切含义。由于子域就是**子领域**，其与子域的区别就是**领域**和**领域限界上下文**的区别。通常子域与领域一一对应是理想的状态，虽然很难，但在DDD设计时必须尽量确保子域和限界上下文一对一映射。

**`{:}`** DDD设计中我们并不是关注所有的领域对象，而只需着重关注那些**核心业务对象**。

**`{:}`** 领域专家不是一种特定的职业，所有对领域业务精通的人都可以称为领域专家，他们可以是CEO、CTO、需求分析人员、业务操作人员、产品人员甚至架构师等等。

**`{:}`** 领域对象建模分为两个阶段：

+ 战略建模

着重于概念层面，基于领域通用语言和领域限界构建领域对象的概念模型。

+ 战术建模

着重于实现层面，使用聚合、领域服务、值对象、领域事件等手段构建领域对象的实现模型。

战术建模比战略建模更加复杂。

**`{:}`** 架构师充分理解领域的**复杂性**，是领域对象建模的成败关键。

**`{:}`** DDD与TDD(测试驱动开发)的过程类似，也倾向于测试现行，即在构建领域对象前，先构建测试用例代码。其中重要的一点是，**一定要尽最大程度的使用真实的领域数据作为测试数据**。

**`{:}`** DDD强调领域模型驱动DB设计，同时DB中的表字段应当与对应的领域模型中的名字保持一致，比如领域对象属性backlogId在DB中对应的字段应当命名为backlog_id。

**`{:}`** 领域模型需要迭代式完善，每一次迭代我们都必须仔细思考先前的假设、模型中的概念是否保留、某个概念是否属于核心域等等。

**`{:}`** 

**`{:}`**

**`{:}`**

**`{:}`**