**声明：** 所写均为个人阅读所思所想，限于知识层次和结构，难免有错误遗漏之处，请批判阅读。探讨可循：<mr.geek.ma@gmail.com>

* * *

## 定义

协议就是合同、契约或共识，通俗讲就是多个个体之间的约定。人类的语言就是一种约定，所以可以称为“人类通信协议”.不同的国家名族之间有不同的语言，因此，自然而然的，需要对两种语言进行翻译（映射）。计算机世界的通信协议与人类语言具有类似的语义，以下的讨论全部局限于计算机远程通信协议。<!--more-->

## 必要性

**沟通、通信、传递信息**

> 计算机世界中，所有的数据都是0和1。在网路环境中，两个终端之间需要互相交互信息时，传递的都是一段一段的二进制流。终端接收到二级制流后，需要按照一定的方法(根据某种约定好的标记），将二进制流转换为“可读”的信息，此处的可读不单指人类可读的信息（比如：文本，图像，音频等等），也包含（接收端）应用程序可以理解的“结构化”的二进制。比如某个bit代表的是一个boolean值，某一段32bit是指一个无符号32位整数等等。

## 分类

*   根据OSI模型 
    *   物理层协议
    *   数据链路层协议：MAC
    *   网络层协议：IP
    *   传输层协议：TCP, UDP
    *   应用层协议：HTTP
*   根据应用范围 
    *   通用协议：互联网中普遍被接受和实现的协议，如HTTP, TCP/UDP, IP等
    *   专用协议：各类应用程序自定义协议，如XMPP等
*   根据编码方式 
    *   二进制协议：二进制流的结构约定（共识），如TCP。不一定限定于应用层。更紧凑。
    *   文本协议：使用通用编码集（ASCII, Unicode, GBK等等）的二进制协议，如HTTP。限定于应用层。 

<pre>注：
    两者的区别类似于文本文件和二进制文件的区别，不是物理上的（因为所有数据都是二进制），而是逻辑上的。
    文本协议基于字符编码文件的，如ASCII，Unicode，由于编码文件通常都是人类文字和二进制byte数组的映射关系，因此，文本协议对于人而言，更加易读。文本协议通常\r\n代表着消息之间的分隔符。
    而二进制协议，一个或者多个byte代表什么意思，完全自定义，比如2byte可以代表字符A，也可以代表字符B，也代表一个整数C，代表整数时，还需要规定字节顺序（大端和小端）。
</pre>

<pre>注：
    大端排序：低地址（索引）存放高位字节；小端排序：低地址（索引）存放低位字节。TCP网络流统一规定使用大端排序，JVM统一使用大端排序。
</pre>

*   其他分类方式

## 基于TCP的应用协议的特点

*   数据包无逻辑分界标记

<pre>标记方式：
    1. 定义包的长度，如下：
    ---------------------
    | 2-Bytes  | N-Bytes|
    ----------------------
    | Body-Len |  Body  |
    ----------------------
    2. 定义包的结束标记
    ----------------------------------
    | N-Bytes   | M-Bytes             |
    ----------------------------------
    | Body      | End Tag, eg. \r\n   |
    ----------------------------------   
</pre>

*   互联双方不可感知状态

<pre>注：
    1. 依赖TCP自身心跳包，这通常都依赖于OS的实现，频率的调整需要修改OS参数。
    2. 自定义一定频率心跳包，更灵活的方案。
</pre>

*   基于有状态连接

<pre>注：
    在网络可能频繁切换的环境下（如移动应用环境），会导致“连接震荡断开”，这并不是一个简单的问题，可能的解决方案可参考:http://blog.codingnow.com/2014/02/connection_reuse.html
</pre>

## 基于UDP的应用协议特点

*   传输包的大小限制

<pre>注：
    每个数据包小于64KB，因此，对于大数据包，需要组合解析多个包的内容
</pre>

*   无连接

<pre>注：
    传输不可靠，可靠性需要自定义机制保证
</pre>

## 协议加密算法

*   DES：对称可逆加密算法，老牌算法，因安全性问题，逐渐为AES替代。
*   AES：对称可逆加密算法，也称为Rijndael算法，替代DES成为新的推荐标准。
*   RC6(4)：对称可逆加密算法，在无线传输和串行流传输的加密领域占有相当的分量。
*   RSA：非对称可逆加密算法，是目前所有敏感领域（如银行，支付）的事实标准。
*   MD5：哈希不可逆算法，在网站登录、操作系统的用户认证、文件完整性和数字签名等领域广泛应用。
*   SHA：哈希不可逆算法，在网站登录、操作系统的用户认证、文件完整性和数字签名等领域广泛应用。

## 常用通信协议

#### 结构化数据协议

*   [XML][1]: W3C组织定义的标准结构化数据格式，配合SOAP协议，是WebService的构建基础。也可以配合其他协议，如HTTP、TCP。
*   [JSON][2]： Javascript语言内建的结构化数据（即对象）格式，准确说，它并不是一种通信协议，只是一种数据格式。

#### RPC协议

*   [SOAP][3]: 互联网应用RPC协议的事实标准，但由于性能问题，企业软件开发中应用更广泛，互联网软件开发中较少使用。
*   [RMI][4]: Java平台的RPC标准
*   [.NET Remoting][5]: .NET平台的RPC标准
*   [Google Protobuf][6]: Google开源的跨平台RPC协议，配有代码生成工具。
*   [Thrift][7]: Facebook开源的跨平台RPC协议，配有代码生成工具，已贡献给Apache基金会。

 [1]: http://en.wikipedia.org/wiki/XML
 [2]: http://json.org/
 [3]: http://en.wikipedia.org/wiki/SOAP
 [4]: http://www.oracle.com/technetwork/java/javase/tech/index-jsp-136424.html
 [5]: http://msdn.microsoft.com/en-us/library/vstudio/72x4h507.aspx
 [6]: http://code.google.com/p/protobuf/
 [7]: https://thrift.apache.org/