---
author: "patrick.unicorn"
date: "2014年11月02日"
output: 
  html_document:
    theme: null
    highlight: null
    css: ../css/main.css
---

天才向左，疯子向右
====

**声明：** 所写为个人所读所想，限于知识层次，请批判阅读。

* * *

## 前记

花了6个小时，一口气把[《天才在左，疯子在右》][1]看完了，和《挽歌》一样，这也是一本读完给人以极大思想波动的书。不同的是，这本书是纪实性的,并非杜撰式的小说，呈现了作者四年间采访过的各式各样的“精神病人”的内心世界，有狂躁症、性格分裂症、妄想症等等。其中有些患者也许我们并不能简单的将他们归为”精神病者”，甚至他们的很多思想不能称之为“妄想”，只是不被这个时代大多数的“平常人”所理解。我一直认为在思想的自由上，不赞成“多数原则”，因为我们的思想总是有“时空局限性”。以“平常眼光”来看，那些“少数者”在这个“平常世界，平常时代”活得并不“幸福”。

从题材来看，这是本略显“负能量”的书，书中的某些想法具有很强的”传染和危险”性。我建议读的时候带着`“看小说”`的心态阅读，不可过于偏执纠结于那些患者的思想和行为的缘由。我最感兴趣的是书中一些关于宇宙和人类的“超前”思考，这样“神经”的思考也只有“精神患者”才能想象出来，确实足够震撼和开拓读者的世界观和思维方式。

<!--more-->

## 插曲

翻看网易阅读的时候无意中看到了，觉得挺有意思，就随口提了书名，没想到老婆之前就买过这本书，说是推荐我看看，但是她不许我一口气看完了，说是怕我太沉浸于其中了，变“神经病”。之后在和老婆探讨人性中潜藏的阴暗面时，她神秘兮兮的对我说：“其实我也有过很阴暗的想法”。这一下勾起了我的好奇心，赶紧追问之，老婆死活不说，说这是她心底的秘密，已经埋藏很久了。最后，在俺的再三纠缠之下，老婆一本正经的表情说“我想抢银行”，我瞬间就石化了，忍不住的大笑啊，怎么想也没想到，这就是老婆所谓的“很阴暗”的想法，我邪恶了...

## 启示

+   阅读应该总是以“批判性心理”开始。

+   “允执其中”，不偏执过去将来，不偏执失去获得。

+   当世社会的大多数人都过于浮躁，沉醉于所爱的少之又少。

+   最恐惧的是“人心”，最难懂的也是“人心”。

+   不要恐惧于“未知”，思索的过程是宝贵的，结果只是个“附属品”。

+   有些事是无解的，只问经历，不必问缘由。

+   质疑一切，但不要（极端方式）否定一切，请相信“存在即合理”。

+   我们终将失去最宝贵的“生命”，请提前做好失去一切的心理准备。

+   《易经》过于玄妙，《论语》过于世俗，唯有《老子》在世界观和人生观之间较为平衡。

下面是一篇豆瓣的书评[他们只是把头埋在沙子里的驼鸟][2]，是对这本书的**反思和批判**，我觉得很深刻。


* * *

<blockquote>
　　 
在我看来，这本书的所谓启迪，恰恰不是想象力那一面，而有可能是毒害。我对这本书在豆瓣上的很高评价感到深深的担忧。我想，这么多人给它打了高分，只是因为这是一个很新的题材，满足了很多人的好奇心，但是大家都忽略了其负面影响的那面。精神病人的思维其实是非常危险的，很多人仅仅只是病态，我当然不排除其中的一部分很天才。很多人都不了解精神病，所以对它好奇甚至是浮想联翩。 

我想我很有资格深入这个问题，因为我在16岁时，是个心理问题非常严重的小孩。我曾经深深地陷入了现实和理想的纠缠中无法自拔。我也问自己，人为什么要这么生活？为什么不建立一种新秩序？为什么要这样？为什么要那样……但是由于当时很年幼，我也没有得出任何结论。 

现实中生存的人，都被罩在一张无形的网里，这张网就是从小形成的世界观、人生观。但是，精神病人是由于某种原因或者刺激脱离了这张网的人。他们站在网外，质疑现实那张网的合理性，并在编织自己的那种网。所以，很多精神病人他们都有貌似很强大的逻辑，就是因为他们在不断的编织和形成自己的那个网，来对抗现实的网。 

我曾经花了2年时间，几乎脱离了现实的网。但是由于各种外界因素，或者我不太聪明或者我很走运，我没有形成自己的网。但是，我花了4年时间说服自己和完全正常，彻底认清现实和理想的关系，彻底分清楚有益和有害的思想。那6年，是人生最如花的年纪，从17岁到22岁。 我没有读过心理学或者精神病学的书，但是我不断的在和自己沟通，在说服自己，在帮自己找到回归现实的路。这是个非常漫长和无比痛苦的过程。没有体验过的人，根本就就无从知道其中的艰难。但是精神问题非常复杂，我只是其中一种。 
我在初中是个成绩特好的小孩，年年年级第一。我当是的状态是拼了命也要考第一，我的生活全部内容就是学习那些书本的东西，完全忽视了建立人生观和世界观。当时，我在大家的眼里是个优秀又漂亮的小女孩，好像什么都好。几乎来自所有人的夸奖，让年幼的我自信心膨胀到无限大。但其实这种自信心的唯一根基，就是我成绩第一。所以我拼了命也要保持这个记录。 

噩梦从高中开始了。这也让我相信，当人生的轨迹走到顶峰时，后面就是不断地下落、下落。高中是一所省重点学校，我的成绩本来进校也排在中后的位置，支撑我自信和自尊的那个唯一一下就没有了。再加上我性格非常内向，且极为单纯，我发现——很多人不光成绩好，还有性格好，外表好，家境好；而我什么都没有了。 

我的那个本来就脆弱的世界观，就在不断的坍塌和崩溃。于是，我就开始问自己，究竟人活着意义（是什么）？社会究竟是怎样的？由于我本来就很内向，几乎自闭，我没有从家庭、朋友、同学的渠道去了解社会，去寻求答案，我只是通过了书本来寻求解答。当时我就胡乱的看一些书，反正很杂。但是看了后我就更加迷茫，我在逐渐陷入一个怪圈，就是我在想——人活着的意义和人究竟要怎样生活？社会目前的状态是合理的吗？又是如何形成的？

我每天就在不断的想，上课想，下课想，简直进入了疯狂的状态。我觉得这些问题关乎人类生死存亡，自己有非常重大的责任去想清楚。甚至觉得，为什么就我意识到了这一点？而其他的小孩都只是埋头在备战高考——所以，足于证明我的特殊性和我的重大责任。但其实，我什么结论都没有得出。因为这些问题都太巨大了，以我当时的水平是无解的。但我当时并不这么认为，我执迷不悟，疯狂求索。 

其实，这是脱离现实和编织那个怪异的网的开始。这其实就是个恶性循环，只会导致我更加与现实格格不入。我当时的问题是缺乏世界观和严重的性格缺陷，但思考这些无解的问题，只是更加加速了我滑离现实的脚步。我开始觉得现实很肮脏可鄙，人类的行为很丑陋可憎，只有那个理想才是高贵的。于是，我要彻底放弃现实，投奔理想。我觉得自己异于常人，但是肯定高于常人。这样的想法也会导致我表现在行为上。有些同学觉得我有病，家人也觉得我有问题。但是由于我表现的并不明显，且我一直都是很逻辑的在思考一切（我本身就是一个理性远多于感性的人），所以我在整个过程中都很理智。这也是我为什么没有出现任何精神崩溃的主要原因。虽然，我大脑里每天都在进行激烈的思考斗争，和感受来自现实的极大压力(高考和我与现实的格格不入) ，但是理智和逻辑一直在稳住我的整个状态。 

高考后，我进入了一所野鸡大学。由于在军校内，所以实施封闭管理，导致我没有任何独处的时间。这也在很大程度上遏制了我脱离现实的问题。也是各种机缘巧合，命运安排了一个很优秀的女孩子和我同寝室同班，所以我们自然而然成了很好的朋友。她是个非常有主见、有理想、性格也很好的人，军校和她，可以说是导致我回归正常的重要因素。军校让我不得不面对现实，因为我找不到地方独处，几乎任何时候周围都是人。由于封闭管理，我想跑出去也出不去。而她的非常正面的思维和性格，成了影响我和让我模仿的榜样。 

高中的我几乎不被同学接受，没有朋友。因为大家都忙着考试，所以很正常的觉得我很怪、很可笑，迟早要出问题。但是，他们的态度和我当时面临的高考压力，让我更加觉得现实可憎，更加陶醉于脱离现实带来的快乐。但是，当我开始有了知心朋友，和我开始逐渐被寝室人接受以及喜欢的时候，我觉得现实对我开了一扇小小的门，我开始逐步告诉别人我的困惑。由于我一直在行为上都很正常，且我有可爱的一面，大家都完全的在接纳我。我开始反思现实和理想的关系，以及改变自己的性格。其实，这就是我开始步入良性循环的开始——纠正和建立我的世界观人生观以及改正我的性格缺陷。 

我是三月底出生的白羊。俗话说三月黄，人痴狂。人到了三月份就容易亢奋和活跃，很多人犯病也是在三月份。三月份出生的人，本质上就有进入精神歧途的潜质。我也是个非常典型的白羊，精力旺盛，好奇心强，内心活跃，喜欢思考本质的问题，容易偏走极端，内心单纯。这样的本质，必须搭配一个非常外向和开放的性格。 我内向的性格很早就让我感到无比压抑，我也意识到一定要成为外向的人。但是，改变性格也是一件非常困难的事。但是，经过若干年的努力，我已经成功的把自己从一个内向、封闭、自卑、几乎没有朋友的人，转变为了一个很外向、活泼开朗、很讨人喜欢的人.。 

小打岔了一下，重新回到我开始反思现实和理想的关系。其实，正常人很难理解和体会——脱离现实是种什么感觉。因为，大家都罩在那个无形的和让你察觉不到的大网，这个大网就是在你从小长到大、外界给你成功输入的、正常的、人生观和价值观。总体而言，全世界的人都有类似的关于如何生活的概念。但有些人又是如何脱离这种网的呢？无外乎两种，一种是本身世界观就很脆弱，人生观模糊，以及现实的失败，会导致他们开始反思眼前的这个网。很理智的病人，就开始逻辑上构思新的网。 

这就是书中提到的，那些貌似逻辑无懈可击的天才在进行的事。但是谁也无法证明那个网的正确性。当然，书中提到了人类的证明本身就很可笑，那我们凭什么相信那个网是天才的、是有预见性的、是真理呢？这也是当时我走的路，只是我走了个开头，就由于外界的因素给拉回来了。但是很多人只是越走越远，他们开始把自己的网越编越大，越编越无懈可击。但其实，所有的一切说白了，都是妄想、臆想、假象，也就是胡思乱想。但是，由于他们的网看起来非常无懈可击，很有说服力，如果想让他们回归正常，就必须有一个更加强大的逻辑，把他们的网一点点粉碎和推翻。但是，很多时候精神科医生都很难做到粉碎和推翻他们的网，所以也无法让他们正常。但是，为什么他们的网会貌似无懈可击呢？因为织网是他们对抗现实的唯一手段。 

他们要抵抗现实，必须不断织网；他们只有把网结的足够强悍，才能抵抗现实的入侵。如果一个人总是在做一件事，肯定在这件事上会有很大进展，这也是规律。所以，他们会通过各种办法证明自己的网存在的可能性。但是，我觉得很多网都是有漏洞和问题。但是，很少有人或者医生花大量的时间去研究或者是破解他们的那些网，并且捣鼓那些东西也是危险的，会把你不小心带进去。所以真实的情况是，只能让他们继续像个忙碌的蜘蛛在结网。但是，我只是脱离了，还没有形成网，或者只是非常零星的点。所以，导致只要我感到现实还有空隙接纳我，我就会想着回来。当然，也许是我不够聪明或者天才才结网失败，呵呵。 

还有一种情况，就是某些人由于巨大的刺激让它无法面对现实，由于精神的自我保护让自己处于休克状态，于是也飞出了网。前种情况的离开现实，是缓慢的脱离，也是理智地；但是后者的飞就是瞬间的，这种也容易发生在过于感性敏感和性格脆弱的人身上。 

但不管怎样，脱离现实都是目的和结果。我大概花了2年时间，在说服自己要看清现实和理想的关系。我也会找很多理由，去说服自己，给自己心理暗示。肯定有人要质疑——为什么要花这么久？因为，一旦脱离了心理，就会对现实产生巨大的反力。当我越想回来，我心理的那个反力就越是往后拉。我唯一能做的，就是不断和自己沟通，其中的过程也非常痛苦。 
其实，回到高中我开始想结网和每天胡思乱想的时候，那时的脱离对自己是种解脱，让人觉得很轻松很快乐。并且，思考一些貌似伟大的问题，会给与自己自信和自尊。我当时就觉得，自己到了一种空旷辽阔和无比美好的状态，是和当我面对现实完全不同的感受。面对现实，只是大家都不喜欢我，家人的失望和高考的逼迫；但是一旦我出来了，或者开始思考那些问题，我就完全进入了另外一种状态。当时，我也看王小波的书。我很坚定的觉得，自己找到了精神家园和那片干净的沃土。所以，我要呆在那个地方，放弃现实。面对现实，我就感觉很自卑和挫败感；而我的自负、积极、奋进，只能在那个看不见的理想中弥漫和伸展。 

但其实，关于那个理想是什么？在哪里？我是没有答案的，因为我只是处于结网的开始。但是，当我决定，我要重新回到现实正常生活时，我又陷入了深深的心理拉锯战中。虽然，我一直都过着正常的生活，但是我心里还是想着，是否可以找到一个新的生活方式。如果要完全正常，你只有完全接受现实。我的潜意识在说，不要放弃理想，那是种堕落，因为现实是可憎和平庸的。实际情况就是，当我大脑里有一种力量告诉我，要完全认可和接受眼前的现实时，另一种力量就在奋力反驳、否定现实、寻找理想。我当时真的很不愿意完全认可和接受眼前的生活方式，我觉得我要不同的东西，但是不同的是什么，却是个空白。但当时，我已经停止了脱离的脚步了，我在逐渐回来，我每天就像个唐僧一样的告诫自己——完全接受眼前的一切，这就是人类的生活方式。 

其实，心理暗示的作用是非常大的，只有通过不断的暗示，才可以让自己完全记住我该做的。之后，我又花了2年时间，让自己完全正常，我让自己完全的感受现实的力量和接受现实的网的约束。我当时觉得，只有接触户外才能快点找到回来的路。于是，我上课都挑些靠窗的座位，我尽量花时间和同学在户外散步或者休息。后来，学校管的不严了，我就想办法出去，到大街上胡乱走。我当时觉得，在大街上走路，是回归现实的最好的途径。我一条街一条街的走，有时一天走4-5个小时，就是多感受现实的力量。其实，我也不知道这种方式是否正确，但我当时就是这样的。我也几乎走了大概2年。现在想想自己真是可怜，一个20岁左右的女青年每天在大街上四处游走，寻找回到现实的感觉。但这也是一个非常痛苦和极端无奈的方法，我也是在不断说服自己，在和心理的那个反力做对抗。看着别人都可以正常的生活和学习，而我只能纠缠于让自己接受现实这类破事，我就觉得很痛苦。但是，我没有其它的办法了，这都是我为成长和自己步入精神歧途所犯下的错误的更正。 

但是，我已经越来越正常。使我真正完全接受所有的一切的是，我开始参加工作的半年后，我已经和常人想的完全一样，心里的那个理想或者说是恶魔（我当时就觉得那是个恶魔）已经被我完全的抛弃了。但其实，整个过程也是我改变性格和树立正确健康的人生观、价值观、世界观的过程。这就是回到了那个导致我犯错的原点了，我绕了很大的一圈，付出了惨痛的代价，浪费了非常宝贵的6年青春，高中和大学几乎什么都没学进去，只是在现实和那个如恶魔般的根本不存在的理想中挣扎。但我也成功的解决了我的性格缺陷和世界观的问题。 

这6年的整个过程中，有很多痛苦的片段，有太多拉扯的疼痛。准确说来，就是我首先必须意识到我病了，然后我要分析我为什么病，之后是怎么去治好。其中，要不断地分析自己的过去，剖析成因，要不断的和自己沟通，去说服自己接受和面对现实。我想，如果不是靠着我顽强的意志力和非常乐观的性格，以及理智的分析，是很难完成的。也许我现在已经彻底崩溃了，或者还是陷在那个泥潭中苦苦挣扎。但是现在的我已经完全正常，我也成为了一个非常独立、有主见、认真工作和生活的女子。 

其实，我把我的整个经历写出来的原因，只是想说明，脱离现实和误入精神歧途是件非常可怕和悲惨的事，绝对不是什么想象力的问题。因为，他的那些所谓的思想和行为，没有对他自己和社会起到任何正面的作用；相反，他只是在不断欺骗和麻痹一个人，就是他自己。他不断地让自己相信，自己的网有多么好多么伟大，但是社会和现实是不会被欺骗的。当然，不排除一些人真的非常聪明智慧，想出了有可能正确的东西，但是他完全可以在现实的过程中去继续一切啊！为什么要剑走偏锋呢？总之他们就是病了，即使天才也是没有任何意义的天才，要回归现实才是唯一的王道，这对他们、对社会都是最好的结果。 

并且，这本书也在某种程度上打开了一个潘多拉的盒子。其实书中讲述的很多人的想法都很怪异，看世界角度也很诡异。但我觉得首先这就是种病态，虽然我现在没有摆出很多强大的理由来反驳。当然，我也不想花那个时间研究。但是我觉得，如果在人群中弥漫这种思维，只是让一些精神脆弱的人误入歧途。所以，建议这本书只能当小说来看，笑笑或者吓吓就够了，然后忘掉它。 

当然，也希望大家能够用更加宽容的态度对待这个群体。首先，他们真的非常非常可怜和悲惨，所谓的脱离现实、也就是在精神和认知上被世界抛弃了的人。他们比一贫如洗的穷人更加可怜，他们在社会中找不到认可和安全感，所以才编织自己的那张网。不管那张网看似多么强大，他们都是极端孤独和脆弱的。因为我们都是群居在一起生活的动物，但是他们住在只有一个人的网里，他们其实非常渴望现实的接纳，那是让他们有可能回来的唯一要道。但是，如果这些人不幸生存在一个被排斥、被打击、被侮辱的环境里，只能是让他们彻底放弃眼前的生活，死心塌地的继续织网。 

我想特点说明的是，精神有问题的人有个共性是——都排斥现实。他们都会觉得，现实如何如何，给你描述他的想法如何如何。但是任何人都可以保有任何奇思怪想、但是很现实的生活。因为现实并不排斥任何奇思怪想，只是你要很现实的去认识和处理它们之间复杂微妙的关系，学会把奇思怪想放在一个特定的地方就行了。很多人在物理学上、哲学上取得了巨大的成就，他们的想法在当时看也很奇怪，但是他们还是很现实的生活。人要学会辨别有益的奇思妙想和纯粹的妄想臆想， 虽然它们有时长的很像，但有本质区别。当然，这也是个很巨大的话题，我们也不深究，但肯定是有区别的。 

所以，任何放弃现实而追求纯粹理想的人都是有病的人。因为现实不拒绝任何理想，只是你自己如何处理的问题。而他们之所以排斥现实的唯一解释，就是他们不知道怎么在现实中生活，而绝非他们有什么奇特或者思想，更与天才没关系。所以，这是我非常讨厌书的作者冠之以天才或者有可能天才的原因，这只会对大众形成误导。而书这样起名字，也无非是为了吸引眼球，在经济利益前忘记了做人的本分。 

最后我想说明，我没有读过什么心理或者精神学之类的书，我也懒得去理解那些貌似高深的东西。文中所述的各种观点很可能错误，因为这只是我自己的经验总结，但是都是真实的，我没有必要也没有能力去杜撰这么个并不好玩的故事。 

我也觉得，这样的一本书会对20岁以下的青少年会产生一些负面的影响。通常工作后还会读书的人，都是比较上进和积极的人，读这样的书也只是猎奇，过后就忘了。但是青少年的人生观很脆弱，任何小事或者小的问题在他们眼里就会被自动放大。他们通常会很认真地去读书，如果也模仿书中的怪异甚至病态的思维去看世界，恐怕只会误入精神歧途。 

顺便推荐我写的其它文章: [《绝对的阳光来驱散人生的阴霾》][3] [《不能做苟且的自己》][4] 

</blockquote>

 [1]: http://book.douban.com/subject/4242172/
 [2]: http://book.douban.com/review/3288269/
 [3]: http://www.douban.com/note/75923780/
 [4]: http://www.douban.com/note/132379032/