## 没有成功经验的老板

如果你的老板经常沾沾自喜地说：“我经历过的事情太多了，像我这样垮下去又能站起来的人毕竟不多，我有我的独到之处。”这时你就应该怀疑自己的老板了，如果不是他有某些重大的缺点，他不会总是经历失败，一个没有成功经验的老板，怎么能肯定下次一定会成功，除非你有吉人天相的“帮人命”。

## 事必躬亲的老板

如果你的老板常说，“每一件事，我不经手就一定会出差错”，并以之为豪的话，你就应该想到，这位老板肯定留不住人才。老板不问大小事都要亲自参与，他怎么能期待下属独立工作？特别是在事必躬亲的老板不在场的时候，无法独立的下属出错的机会就更多。一位有创意、具备独立工作能力的人，绝不希望这样的老板常在身边。

<!--more-->

## 朝令夕改的老板

这样的老板可能在不断给你新指示，你花费许多时间策划的费数月酝酿的一个计划，可能因为他一句话而宣布作废。这样公司上下天天都会很忙，但大家忙的却是收拾残局、挖东墙补西墙的工作。

## 喜新厌旧的老板

每个公司都会有几位“开国元老”，时间长了你会发现这类“国宝级”的员工，在江山稳定之后却被“杯酒释兵权”了。这类公司通常员工流动率极高。与这类老板共事，通常都会有一段“蜜月期”，其固定模式如下：一进公司，老板便经常在你面前数落一些资深员工这里不好，那里不是，而夸奖新员工如何如何优秀。在“蜜月”后期，你就会从老板那儿听到那些新进来的员工也有许多的不是，接着就会看到不断有员工戏剧化离职的事件，理由都是这些员工不能用，不适合公司需要。当然，同样的故事最后也会发生在你身上，在你主动辞职或老板以某种婉转的形式请你走的时候，他仍会告诉你：“我们以后还是好朋友。”实际上你做了99件好事，但第100件事办砸了，你就很难在老板面前翻身了。
    
## 感情生活复杂的老板

工作不能搀杂风流韵事是一条铁律，而这类老板往往将最宝贵的时间都耗费在感情纠纷上。他喜欢雇用年轻漂亮的女员工，也喜欢用感情处理人际关系；他终日拈花惹草，绯闻不断，只要有女人在场，他就头脑发晕。这类人当然也无法冷静地经营企业。
    
## 鱼与熊掌都想兼得的老板

既要马儿跑，又要马儿不吃草，这种老板只能称为不知何所取，也不知何所舍的人。鱼与熊掌都想得的老板，通常是二者都得不到，或许常常因小而失大。成功的老板应该懂得什么是放长线钓大鱼，想捉鸡又不想蚀把米的老板，到最后一定是两手空空。
    
## 多疑的老板

这样的老板所持的观念是人治胜过法治，这类公司通常没有上轨道的制度。如果你是一个部门主管，你经常会在非工作时间接到老板的电话；如果你是基层员工，他也经常会对你表示不痛不痒的关切。跟着这样的老板工作，心理负担之重可想而知。更可怕的是，属下经常有无处可申的不白之冤。

## 言行不一的老板

这类老板最常说的一句话就是：“赚这么多钱对我并没有什么意义。”实际上，企业发展的最重要任务就是追求利润，利润是公司生存的惟一命脉，又何必自命清高加以否认呢？或许你有可能与这类老板共进午餐，在一盘鸡肉上桌之后，老板会忙着为属下夹菜，到头来细心人会发现，骨头特别多的部位都在员工的盘子里，老板却在津津有味地享用着为他自己保留的鸡大腿。

## 甜言蜜语的老板

一般说来，老板不可能听到批评还会心花怒放，因为爱听好话和喜欢奉承是人的天性，但如果善意的批评和宝贵的建议也听不进去，并因此影响了员工在公司的发展，则人人都会噤若寒蝉。

## 心胸狭窄的老板

如果你的老板在看这篇文章时怒火中烧，那就应归为心胸狭窄的老板。 


**在上述10项特质中，如果你的老板具备3项以下，你仍可安心工作，但要记着找机会影响他，增加个人含金量；如果你的老板具有4到6项特质，你最好多花一点时间充实自己，并随时留意报上的招聘广告；如果你的老板具有7项以上的特质，惟一的劝告是：走为上策。**