---
author: "patrick.unicorn"
output:
  html_document:
    css: ../../css/main.css
    highlight: null
    theme: null
---

Java碎碎念之性能
===

**声明：** 所写均为个人阅读所思所想，请批判阅读。

<quote>
读书笔记之目的，一在加深理解、巩固记忆，二在摘取精要、厚书读薄。 -- 无名
</quote>

* * *

读《Java程序性能调优》笔记，外加自己的一些实践经验总结。

## 性能指标

+ 执行时间

一段代码运行到结束的时间。

+ CPU时间

函数或线程占用CPU时间。

+ 内存分配

程序运行时占用内存。

+ 磁盘吞吐量

描述系统磁盘I/O的使用情况。

+ 网络吞吐量

描述网络I/O的使用情况。

+ 响应时间

系统对用户行为或者事件作出响应的时间。响应时间越短，性能越好。

## 调优层次

### 设计调优

从架构设计层次调优。比如架构单独的分布式缓存层。

### 代码调优

针对局部代码片段。比如常见的低延迟网络程序中，需要关闭Nagle算法，因此需要设置socket的nodelay属性等等。

#### 字符串

+ StringBuilder

由于String的不可变性，对于大量字符串的`+`接操作会占用过多的内存空间，性能低效还可能内存溢出。如果只是字符串常量的`+`，那么编译器会进行自动优化。而字符串变量的情况，则需要使用StringBuilder优化。

默认情况下，其capacity为16。如果超出容量，会在原有容量上加倍扩容。因此，对于容量字符串，如果能够预先估计好StringBuilder的容量，那么可以提高性能。

+ subString

<pre>
String a = "abc";
String b = "abc";
String c = new String("abc");

a==b; // true
a==c; // false
</pre>

该函数内部实现时，使用了public String(char value[], int offset, int count)，而该构造函数为了提高性能，采用了偏移量方式，即截取的字串对象其实包含了被截取字串的所有内容，仅仅是通过标识偏移量和长度来确定实际取值。这种方式以空间换取时间，但是当原始字串很大时，多次调用该方法有可能导致内存溢出。

<pre>
String a = "<one long string>";

// 空间换时间，速度很快，但如果多次执行可能会导致内存溢出
a.subString(0, 2); 

// 重新生成一个字符对象，使得subString方法返回的字符对象失去强引用，
// 可以被垃圾回收，避免内存溢出
new String(a.subString(0, 2)); 
</pre>

<quote>
其他依赖public String(char value[], int offset, int count)构造函数的字符串方法，也可能有同样的问题，也应注意。
</quote>

+ split

split支持正则表达式，功能强大。但是对于简单的情况，可以使用功能单一性能更高的`StringTokenizer`。
也可以直接使用高效率的`indexOf`和`subString`配合实现分割字符串，这样性能最高，但是维护性较差，只有当性能非常敏感时才值得考虑自定义实现。

#### 数据结构

| 类型 | 添加 | 查找 | 删除 | 索引查找 |
|---|:---:|:---:|:---:|:---:|
| T[] | O(n) | O(n) | O(n) | O(1) |
| LinkedList<T> | O(1) | O(n) | O(1) | O(n) |
| List<T> | O(1) | O(n) | O(n) | O(1) |
| Stack<T> | O(1) | - | O(1) | - |
| Queue<T> | O(1) | - | O(1) | - |
| Hash<T> | O(1) | O(1) | O(1) | - |

#### NIO

替换BIO。

#### 技巧

+ 慎用异常

+ 尽量使用局部变量，减少全局变量

+ 位运算替代乘除

会降低可读性，慎用。

+ 表查询替代switch

<pre>
int func1(int index) {
    switch(index) {
        case 1: return 30;
        case 2: return 20;
        case 3: return 80;
        case 10: return 81;
        default: return 10;
    }
}

int func2(int index) {
    // 也可以使用数组
    Hash<Integer, Integer> m = new HashMap();
    m.put(1, 30);
    m.put(2, 20);
    m.put(3, 80);
    m.put(10, 81);
    
    Integer ret = m.get(index);
    if (ret == null) {
        return 10
    }
    return ret;
}
</pre>

+ 使用System.arraycompy函数复制数组

+ 使用缓冲读取IO

|原类|缓冲类|
|--|--|
|InputStream|BufferedInputStream|
|OutputStream|BufferedOutputStream|
|Reader| BufferedReader|
|Writer|BufferedWriter|

### JVM调优

调整JVM的各项参数。比如堆内存等等。

### 数据库调优

+ 避免使用`select *`

+ 使用union all替代union

+ 使用连接查询替代子查询

+ 查询、排序字段建立合适索引

+ 调整数据库参数，如查询缓存等等

+ 慢查询日志设定和统计

### 操作系统调优

调整操作系统的某些参数或系统硬件。
